import React from "react";
import AboutSection from "@/components/about/AboutSection";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const About = () => {
  return (
    <div>
      <AboutSection />
    </div>
  );
};

export default About;
