import { Inter } from "next/font/google";
import "../globals.css";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";

// componnent|default
import Header from "@/components/default/Header";
import Footer from "@/components/default/Footer";
import { ThemeProvider } from "@/components/default/ThemeProvider";

import { NextIntlClientProvider } from "next-intl";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default async function LocaleLayout({ children, params }) {
  // get current locale
  const locale = useLocale();
  console.log(locale);

  // show 404 error
  if (params.locale !== locale) {
    notFound();
  }

  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark">
          <NextIntlClientProvider messages={messages}>
            <Header />
            {children}
            <Footer />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
