import React from "react";

export const metadata = {
  title: "Product",
  description: "Generated by create next app",
};

const Product = () => {
  return <div>Product</div>;
};

export default Product;
