import React from "react";

export const metadata = {
  title: "Contact",
  description: "Generated by create next app",
};

const Contact = () => {
  return <div>Contact</div>;
};

export default Contact;
